DELETE FROM menus WHERE id=54;
DELETE FROM menus WHERE id=55;
DELETE FROM menus WHERE id=49;
DELETE FROM menus WHERE id=56;
DELETE FROM menus WHERE id=14;
DELETE FROM menus WHERE id=15;
DELETE FROM menus WHERE id=16;
DELETE FROM menus WHERE id=33;
DELETE FROM menus WHERE id=34;
DELETE FROM menus WHERE id=35;
DELETE FROM menus WHERE id=37;
DELETE FROM menus WHERE id=38;
DELETE FROM menus WHERE id=39;
DELETE FROM menus WHERE id=40;
DELETE FROM menus WHERE id=43;
DELETE FROM menus WHERE id=47;
DELETE FROM menu_role WHERE menus_id=54;
DELETE FROM menu_role WHERE menus_id=55;
DELETE FROM menu_role WHERE menus_id=49;
DELETE FROM menu_role WHERE menus_id=56;
DELETE FROM menu_role WHERE menus_id=14;
DELETE FROM menu_role WHERE menus_id=15;
DELETE FROM menu_role WHERE menus_id=16;
DELETE FROM menu_role WHERE menus_id=33;
DELETE FROM menu_role WHERE menus_id=34;
DELETE FROM menu_role WHERE menus_id=35;
DELETE FROM menu_role WHERE menus_id=37;
DELETE FROM menu_role WHERE menus_id=38;
DELETE FROM menu_role WHERE menus_id=39;
DELETE FROM menu_role WHERE menus_id=40;
DELETE FROM menu_role WHERE menus_id=43;
DELETE FROM menu_role WHERE menus_id=47;
TRUNCATE TABLE notes;
DELETE FROM menus WHERE name LIKE 'Theme';
DELETE FROM menu_role WHERE menus_id=15;
DELETE FROM menu_role WHERE menus_id=16;
DELETE FROM `menus` WHERE `menus`.`id` = 48;
DELETE FROM `menu_role` WHERE `menu_role`.`id` = 48;
INSERT INTO `menus` (`id`, `name`, `href`, `icon`, `slug`, `parent_id`, `menu_id`, `sequence`) VALUES (NULL, 'Tasks', '/tasks', 'cil-task', 'link', NULL, '1', '1');
INSERT INTO `menu_role` (`id`, `role_name`, `menus_id`) VALUES (NULL, 'user', '69');
UPDATE `menus` SET `sequence` = '2' WHERE `menus`.`id` = 69;
DELETE FROM `menus` WHERE `menus`.`id` = 67;
DELETE FROM `menu_role` WHERE `menu_role`.`id` = 118;
DELETE FROM `menu_role` WHERE `menu_role`.`id` = 119;
INSERT INTO `menus` (`id`, `name`, `href`, `icon`, `slug`, `parent_id`, `menu_id`, `sequence`) VALUES (NULL, 'Notes', '/notes', 'cil-notes', 'link', NULL, '1', '3');
INSERT INTO `menu_role` (`id`, `role_name`, `menus_id`) VALUES (NULL, 'admin', '69');
INSERT INTO `menu_role` (`id`, `role_name`, `menus_id`) VALUES (121, 'user', 71), (122, 'admin', 71);
CREATE TABLE `coda_db`.`tasks` ( `id` INT UNSIGNED NOT NULL AUTO_INCREMENT , `user_id` INT UNSIGNED NOT NULL , `text` TEXT NOT NULL , `priority` SMALLINT(10) NOT NULL COMMENT '1 - normal 2 - medium 3 - high' , `deadline` TIMESTAMP NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `tasks` ADD `title` VARCHAR(255) NOT NULL AFTER `user_id`;
